### ISSUE TITLE
No scroll down bar if matches are more than 8

### ISSUE THREAD

**Issue by vionemc** [spongessuck/gm.typeaheadDropdown#5]
Sometimes there are 1000 matches similar to what we typed. Because of the 8 limit, we can't select the right one. Is there any config allowing the scroll?

**Comment by spongessuck** [comment]
The limit is hard-coded in the typeahead element in the template. You'll have to change it there, as there isn't an option to change it in the directive.

**Comment by vionemc** [comment]
Thanks!
